const myFoo = async (req,res)=>{
    try {
        return res.
    } catch (error) {
        
    }
}